# Generated by Django 4.2.7 on 2023-11-24 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_follow'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='follow',
            table='Follow',
        ),
    ]
