# Generated by Django 4.2.7 on 2023-11-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_follow_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='follower',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='follow',
            name='following',
            field=models.IntegerField(),
        ),
    ]
