# Generated by Django 4.2.7 on 2023-11-29 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_follow_follower_remove_follow_user_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='follow',
            table='Following',
        ),
    ]
