# Generated by Django 4.2.7 on 2023-11-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_follow_follower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='user',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='following',
        ),
        migrations.AlterModelTable(
            name='follow',
            table=None,
        ),
        migrations.AddField(
            model_name='follow',
            name='following',
            field=models.ManyToManyField(related_name='follower', to='user.follow'),
        ),
    ]
