# Generated by Django 4.2.7 on 2023-11-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_follow_following_alter_follow_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='user',
        ),
        migrations.AddField(
            model_name='follow',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
    ]
