# Generated by Django 4.2.7 on 2024-01-09 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_alter_follow_follower_alter_follow_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='follower',
        ),
    ]
