# Generated by Django 4.2.7 on 2023-11-20 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='image',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='name',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='nickname',
        ),
        migrations.AddField(
            model_name='follow',
            name='followers',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
