# Generated by Django 4.2.7 on 2023-11-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_remove_follow_image_remove_follow_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='feed_id',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='followers',
        ),
        migrations.AddField(
            model_name='follow',
            name='following',
            field=models.BooleanField(default=True),
        ),
    ]
