# Generated by Django 4.2.7 on 2023-11-22 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_rename_feed_id_follow_user_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
