# Generated by Django 4.2.7 on 2024-01-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_delete_search'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='nickname',
        ),
        migrations.AddField(
            model_name='feed',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
