# Generated by Django 4.2.7 on 2024-01-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_remove_feed_nickname_feed_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='nickname',
            field=models.CharField(default='', max_length=24),
        ),
    ]
